const recipes = [
      // APPETIZERS
      {id:1,name:"Guacamole Clásico",region:"Appetizers",short:"Fresh avocado dip with onion, cilantro, lime, and chile — the essential starter.",time:"10 min",servings:"4–6",ingredients:["3 ripe Hass avocados","1/2 white onion, finely diced","1–2 serrano or jalapeño, minced","1/4 cup cilantro, chopped","Juice of 1–2 limes","1 tomato, diced (optional)","Salt"],steps:["Mash avocados roughly.","Mix in onion, chile, cilantro, lime, and salt.","Fold in tomato if using. Serve with chips."],tip:"Press plastic wrap on the surface to slow browning."},
      {id:2,name:"Pico de Gallo",region:"Appetizers",short:"Bright chunky fresh salsa of tomato, onion, chile, and cilantro.",time:"10 min",servings:"4–6",ingredients:["4 Roma tomatoes, diced","1/2 white onion, diced","1–2 jalapeños, minced","1/4 cup cilantro","Lime juice","Salt"],steps:["Combine all ingredients.","Season and let sit 10–15 min. Serve with chips or tacos."],tip:"Remove seeds for milder heat."},
      {id:3,name:"Queso Fundido",region:"Appetizers",short:"Bubbling melted cheese, often with chorizo or rajas — scoop with tortillas.",time:"20 min",servings:"4–6",ingredients:["12 oz Oaxaca or asadero cheese","4 oz Mexican chorizo (optional)","Roasted poblano strips","Warm tortillas"],steps:["Cook chorizo if using.","Melt cheese in oven or skillet with toppings until bubbly.","Serve with warm tortillas."],tip:"Oaxaca cheese gives the best stretch."},
      {id:4,name:"Nachos Superiores",region:"Appetizers",short:"Loaded chips with beans, cheese, meat, guacamole, and crema — Valley shareable favorite.",time:"25 min",servings:"4–6",ingredients:["Tortilla chips","Refried beans","Shredded cheese","Cooked asada or carnitas","Guacamole, pico, crema, jalapeños"],steps:["Layer chips, beans, cheese, and meat.","Bake until cheese melts.","Top with guacamole, pico, and crema."],tip:"Use thick restaurant-style chips."},
      {id:5,name:"Esquites",region:"Appetizers",short:"Off-the-cob street corn in a cup with mayo, cotija, chile, and lime.",time:"20 min",servings:"4",ingredients:["4 ears corn, kernels cut","Butter","Mayo or crema","Cotija, chili powder/Tajín, lime, cilantro"],steps:["Sauté corn until lightly charred.","Stir in mayo, cotija, cilantro, and lime.","Serve in cups topped with more cheese and chile."],tip:"Mayo + crema mix gives classic texture."},
      {id:6,name:"Ceviche de Camarón",region:"Appetizers",short:"Lime-cured shrimp with tomato, onion, cucumber, and avocado.",time:"30 min + chill",servings:"4–6",ingredients:["1 lb raw shrimp, chopped","Lime juice to cover","Tomato, red onion, cucumber, jalapeño","Avocado, cilantro, salt, tostadas"],steps:["Marinate shrimp in lime until opaque.","Drain, mix with vegetables and cilantro.","Fold in avocado and serve on tostadas."],tip:"Don’t over-marinate or shrimp turns tough."},
      {id:7,name:"Taquitos / Flautas",region:"Appetizers",short:"Crispy rolled tortillas filled with shredded beef or chicken.",time:"35 min",servings:"4–6",ingredients:["12–16 corn tortillas","2 cups shredded beef or chicken","Oil for frying","Guacamole, crema, salsa"],steps:["Fill and roll warm tortillas.","Fry until golden and crisp.","Serve with guacamole and crema."],tip:"Keep rolled taquitos covered until frying."},
      {id:8,name:"Sopes",region:"Appetizers",short:"Thick masa boats topped with beans, meat, cheese, and salsa.",time:"40 min",servings:"4–6",ingredients:["2 cups masa harina","Warm water, salt","Beans, meat, lettuce, queso fresco, salsa, crema"],steps:["Form thick masa disks, cook, and pinch edges.","Top with beans, meat, and garnishes."],tip:"Keep masa soft but not sticky."},

      // NORTHERN
      {id:9,name:"Carne Asada",region:"Northern",short:"Grilled skirt or flank steak — heart of northern ranch cooking.",time:"45 min + marinade",servings:"4–6",ingredients:["2 lbs skirt/flank steak","Orange & lime juice, soy/Maggi, garlic, cumin, chili powder","Tortillas, onion, cilantro, salsa"],steps:["Marinate steak 1–4 hrs.","Grill high heat, rest, slice against grain.","Serve with tortillas and toppings."],tip:"Northern style often uses flour tortillas."},
      {id:10,name:"Machaca con Huevo",region:"Northern",short:"Dried shredded beef scrambled with eggs — Sonora/Chihuahua classic.",time:"25 min",servings:"3–4",ingredients:["1 cup machaca or leftover asada","4–5 eggs","Onion, jalapeño, optional tomato","Flour tortillas"],steps:["Sauté onion and chile, add machaca.","Scramble in eggs. Serve with flour tortillas."],tip:"Leftover carne asada works great."},
      {id:11,name:"Chile con Queso",region:"Northern",short:"Creamy melted cheese with roasted green chiles.",time:"20 min",servings:"4–6",ingredients:["1 lb asadero/Chihuahua/American cheese","Milk","Roasted green chiles, onion"],steps:["Melt cheese with milk.","Stir in chiles and onion. Serve with tortillas or chips."],tip:"Real asadero gives authentic stretch."},
      {id:12,name:"Burritos Norteños",region:"Northern",short:"Flour-tortilla burritos with meat and beans — born in the wheat-growing north.",time:"30 min",servings:"4",ingredients:["Large flour tortillas","Cooked meat, pinto beans","Optional cheese, salsa"],steps:["Warm tortillas. Layer beans and meat.","Roll tightly."],tip:"Traditional northern burritos are simpler than California versions."},
      {id:13,name:"Discada",region:"Northern",short:"Mixed meats on a plow-disc griddle with chiles and onion — northern cookout favorite.",time:"45 min",servings:"6–8",ingredients:["Bacon/chorizo, ground beef, sausage","Onion, jalapeños, tomatoes","Beer or stock, spices"],steps:["Cook meats, add vegetables and seasonings.","Simmer until flavors meld. Serve with flour tortillas."],tip:"True discada is cooked outdoors on a metal disc."},
      {id:14,name:"Frijoles Charros",region:"Northern",short:"Cowboy beans with bacon, chorizo, onion, and chiles.",time:"1.5 hrs",servings:"6–8",ingredients:["Pinto beans","Bacon, chorizo, onion, jalapeños, tomatoes, cilantro"],steps:["Cook bacon and chorizo, add aromatics.","Combine with beans and simmer. Finish with cilantro."],tip:"Meant to be soupy and smoky."},
      {id:15,name:"Sonoran Hot Dog",region:"Northern",short:"Bacon-wrapped hot dog in a soft bun with beans, onion, tomato, mayo, and salsa.",time:"25 min",servings:"4",ingredients:["Hot dogs, bacon","Soft bolillo/hot dog buns","Pinto beans, onion, tomato, mayo, salsa"],steps:["Wrap dogs in bacon and cook until crisp.","Assemble with beans and toppings."],tip:"The soft bun and bacon wrap are essential."},
      {id:16,name:"Cabrito al Horno",region:"Northern",short:"Young goat roasted or braised — Nuevo León specialty.",time:"3–4 hrs",servings:"6–8",ingredients:["4–5 lbs cabrito or lamb shoulder","Garlic, onion, oregano, cumin, citrus"],steps:["Season and roast covered until tender.","Shred or carve. Serve with tortillas and salsa."],tip:"Lamb is a common home substitute."},

      // CENTRAL / PUEBLA
      {id:17,name:"Mole Poblano",region:"Central",short:"Iconic Puebla mole of chiles, spices, nuts, and chocolate over turkey or chicken.",time:"2–3 hrs",servings:"8–10",ingredients:["Mulato, ancho, pasilla chiles","Sesame, nuts, bread/tortilla, spices","Mexican chocolate, stock, poultry"],steps:["Toast and blend ingredients.","Fry puree, add chocolate and stock, simmer.","Serve over poultry."],tip:"Mole improves overnight."},
      {id:18,name:"Chiles en Nogada",region:"Central",short:"Poblanos stuffed with fruit picadillo, topped with walnut sauce and pomegranate.",time:"2 hrs",servings:"6",ingredients:["6 poblanos","Pork picadillo with fruits and spices","Walnut cream sauce","Pomegranate, parsley"],steps:["Roast and stuff poblanos.","Top with nogada and pomegranate."],tip:"Colors of the Mexican flag; served in September."},
      {id:19,name:"Pozole Rojo",region:"Central",short:"Hominy and pork in rich red chile broth — weekend celebration stew.",time:"3–4 hrs",servings:"8",ingredients:["Pork shoulder","Hominy","Guajillo/ancho chiles","Garnishes: cabbage, radish, onion, lime"],steps:["Simmer pork, make chile base.","Combine with hominy. Serve with garnishes."],tip:"Garnishes are half the experience."},
      {id:20,name:"Cemita Poblana",region:"Central",short:"Puebla sandwich on sesame roll with milanesa, avocado, cheese, and pápalo.",time:"30 min",servings:"4",ingredients:["Cemita rolls","Breaded milanesa","Avocado, Oaxaca cheese, chipotle","Pápalo or cilantro"],steps:["Layer ingredients on roll and press."],tip:"Pápalo is traditional; cilantro substitutes."},
      {id:21,name:"Chalupas",region:"Central",short:"Small fried tortillas with salsa, onion, and optional meat — Puebla street classic.",time:"25 min",servings:"4–6",ingredients:["Small corn tortillas","Salsa, onion","Optional shredded meat, queso fresco"],steps:["Lightly fry tortillas.","Top with salsa and onion."],tip:"Keep them small and simple."},
      {id:22,name:"Tinga de Pollo",region:"Central",short:"Shredded chicken in smoky chipotle-tomato sauce — great for tacos or tostadas.",time:"40 min",servings:"6",ingredients:["Shredded chicken","Tomatoes, chipotles in adobo","Onion, garlic, oregano"],steps:["Blend and simmer sauce.","Add chicken and heat through."],tip:"Freezes well for quick meals."},
      {id:23,name:"Pipián",region:"Central",short:"Pumpkin-seed sauce (green or red) with chicken or pork — pre-Hispanic roots.",time:"1 hr",servings:"6",ingredients:["Pumpkin seeds","Tomatillos or tomatoes + chiles","Onion, garlic, herbs, meat, stock"],steps:["Toast seeds, blend sauce.","Simmer with meat."],tip:"Don’t burn the seeds."},
      {id:24,name:"Enchiladas Rojas/Verdes",region:"Central",short:"Corn tortillas in red or green chile sauce, filled and topped.",time:"45 min",servings:"4–6",ingredients:["Corn tortillas","Red or green chile sauce","Cheese, chicken, or beans","Onion, crema, queso fresco"],steps:["Dip tortillas in sauce, fill, roll.","Top with more sauce and cheese."],tip:"Work quickly so tortillas don’t fall apart."},

      // WESTERN
      {id:25,name:"Birria de Res",region:"Western",short:"Slow-braised meat in spiced chile adobo — Jalisco classic, now popular as beef.",time:"3.5–4 hrs",servings:"6–8",ingredients:["Beef chuck/short ribs","Guajillo, ancho, chipotle chiles","Spices, vinegar, onion, garlic"],steps:["Marinate in adobo.","Braise until falling apart. Serve with consomé."],tip:"Consomé is essential."},
      {id:26,name:"Carnitas Michoacán",region:"Western",short:"Pork confit-style until tender and crispy — pride of Michoacán.",time:"3–4 hrs",servings:"8–10",ingredients:["Pork shoulder","Orange, onion, garlic, bay, oregano","Lard or oil"],steps:["Simmer low in fat until tender.","Crisp exterior. Chop for tacos."],tip:"Don’t rush the low simmer."},
      {id:27,name:"Torta Ahogada",region:"Western",short:"Guadalajara drowned sandwich — carnitas submerged in spicy sauce.",time:"30 min",servings:"4",ingredients:["Birote/bolillo rolls","Carnitas","Spicy tomato-chile salsa"],steps:["Fill rolls, drown in hot salsa.","Serve with onion and lime."],tip:"Roll must be sturdy."},
      {id:28,name:"Carne en su Jugo",region:"Western",short:"Chopped beef in its juices with bacon, beans, and tomatillo broth — Jalisco specialty.",time:"1 hr",servings:"4–6",ingredients:["Chopped beef","Bacon, pinto beans","Tomatillos, serranos, garlic, cilantro"],steps:["Brown beef and bacon.","Add tomatillo broth and beans. Simmer."],tip:"Broth should stay light and bright."},
      {id:29,name:"Sopa Tarasca",region:"Western",short:"Michoacán tomato-bean soup with pasilla, topped with crisp tortilla strips.",time:"40 min",servings:"4–6",ingredients:["Pureed beans","Roasted tomatoes, pasilla chile","Tortilla strips, queso, crema, avocado"],steps:["Blend and simmer base.","Top with crisp strips and garnishes."],tip:"Don’t skip the crispy toppings."},
      {id:30,name:"Morisqueta",region:"Western",short:"Michoacán rice plate with beans, salsa, and meat — Tierra Caliente comfort food.",time:"45 min",servings:"4–6",ingredients:["White rice","Beans, salsa roja","Cooked pork or carne"],steps:["Plate rice, beans, salsa, and meat."],tip:"Simple and hearty Apatzingán staple."},
      {id:31,name:"Uchepos",region:"Western",short:"Fresh corn tamales from Michoacán — sweet-savory young corn.",time:"1.5 hrs",servings:"6–8",ingredients:["Fresh sweet corn","Butter/lard, salt or sugar","Corn husks"],steps:["Blend corn into soft dough.","Wrap in husks and steam."],tip:"Use very fresh milky corn if possible."},
      {id:32,name:"Pozole (Western style)",region:"Western",short:"Hominy stew variations from Jalisco and Michoacán.",time:"3–4 hrs",servings:"8",ingredients:["Pork","Hominy","Garlic, onion, oregano","Garnishes"],steps:["Simmer pork and hominy. Season.","Serve with cabbage, radish, lime, oregano."],tip:"Red in Jalisco; other styles in Michoacán."},

      // OAXACA
      {id:33,name:"Tlayuda",region:"Oaxaca",short:"Giant crispy tortilla with asiento/beans, quesillo, meat, and cabbage.",time:"30 min",servings:"2–4",ingredients:["Large tlayuda tortillas","Asiento or black beans","Quesillo, meat, cabbage, avocado, salsa"],steps:["Crisp tortilla, spread beans.","Add cheese and meat, melt. Top and cut."],tip:"Look for true large thin tlayuda tortillas."},
      {id:34,name:"Mole Negro (home version)",region:"Oaxaca",short:"Darkest of Oaxaca’s seven moles — complex chiles, spices, chocolate.",time:"2.5–3 hrs",servings:"8",ingredients:["Dried chiles, sesame, nuts, plantain, chocolate","Spices, stock, chicken"],steps:["Toast and blend. Fry puree, add chocolate and stock.","Serve over chicken."],tip:"Chilhuacle negro is ideal; good substitutes work."},
      {id:35,name:"Memelas",region:"Oaxaca",short:"Thick oval masa cakes with beans, salsa, and cheese.",time:"35 min",servings:"4–6",ingredients:["Masa","Black beans, salsa, queso fresco"],steps:["Form ovals, cook, pinch edges.","Top with beans, salsa, and cheese."],tip:"Thicker and usually oval vs sopes."},
      {id:36,name:"Chapulines",region:"Oaxaca",short:"Toasted grasshoppers with chile, salt, and lime — snack or taco filling.",time:"15 min",servings:"4 as snack",ingredients:["Prepared chapulines","Lime, chile, salt","Tortillas, guacamole optional"],steps:["Re-toast if needed. Season and serve."],tip:"Nutty, earthy crunch."},
      {id:37,name:"Tamales Oaxaqueños",region:"Oaxaca",short:"Banana-leaf wrapped tamales, often with mole and chicken.",time:"2–3 hrs",servings:"8–10",ingredients:["Tamale masa","Banana leaves","Chicken with mole or beans"],steps:["Spread masa on leaf, add filling, fold, steam."],tip:"Banana leaves add distinct aroma."},
      {id:38,name:"Enchiladas de Coloradito",region:"Oaxaca",short:"Oaxacan enchiladas in coloradito (reddish) mole.",time:"1 hr",servings:"4–6",ingredients:["Corn tortillas","Coloradito mole","Chicken or cheese","Onion, queso, crema"],steps:["Dip in mole, fill, roll, top with more mole."],tip:"Slightly sweet brick-red mole."},
      {id:39,name:"Quesillo",region:"Oaxaca",short:"Famous Oaxacan string cheese — pull into strings for tacos or tlayudas.",time:"Ready",servings:"As needed",ingredients:["Fresh Oaxaca cheese"],steps:["Pull into strings. Use on tlayudas or with tortillas and salsa."],tip:"Best when very fresh and elastic."},

      // YUCATÁN
      {id:40,name:"Cochinita Pibil",region:"Yucatán",short:"Achiote-marinated pork slow-roasted in banana leaves.",time:"4+ hrs",servings:"8",ingredients:["Pork shoulder","Achiote paste, sour orange juice","Banana leaves","Pickled red onions, habanero salsa"],steps:["Marinate, wrap in leaves, slow-cook.","Shred and serve with pickled onions."],tip:"Banana leaves add aroma and moisture."},
      {id:41,name:"Panuchos",region:"Yucatán",short:"Fried tortillas stuffed with beans, topped with cochinita, cabbage, avocado, onion.",time:"45 min",servings:"4–6",ingredients:["Corn tortillas","Refried black beans","Cochinita, cabbage, avocado, pickled onion"],steps:["Stuff with beans, fry.","Top with meat and garnishes."],tip:"Don’t overfill the bean pocket."},
      {id:42,name:"Sopa de Lima",region:"Yucatán",short:"Bright chicken soup with Yucatán lime and crispy tortilla strips.",time:"1 hr",servings:"4–6",ingredients:["Chicken","Onion, garlic, tomato, oregano","Lime","Tortilla strips, avocado, cilantro"],steps:["Make clear broth, shred chicken.","Add lime at end. Serve with toppings."],tip:"Add lime at the end for brightness."},
      {id:43,name:"Papadzules",region:"Yucatán",short:"Tortillas in pumpkin-seed sauce filled with hard-boiled egg.",time:"45 min",servings:"4–6",ingredients:["Corn tortillas","Toasted pumpkin seeds, epazote","Hard-boiled eggs","Tomato sauce"],steps:["Dip in green sauce, fill with egg, top with sauces."],tip:"Sauce should be smooth and bright green."},
      {id:44,name:"Salbutes",region:"Yucatán",short:"Puffy fried tortillas topped with turkey/chicken, avocado, and pickled onion.",time:"30 min",servings:"4–6",ingredients:["Corn tortillas or masa","Oil","Shredded poultry, lettuce, avocado, onion"],steps:["Fry until puffy. Top and serve immediately."],tip:"Lighter and puffier than panuchos."},
      {id:45,name:"Queso Relleno",region:"Yucatán",short:"Edam cheese stuffed with spiced meat, raisins, and olives.",time:"2 hrs",servings:"6–8",ingredients:["Edam cheese ball","Spiced ground meat, raisins, olives","White sauce, tomato sauce"],steps:["Hollow and stuff cheese. Steam or bake.","Serve with sauces."],tip:"Celebration dish; mild cheese balances filling."},

      // GULF
      {id:46,name:"Huachinango a la Veracruzana",region:"Gulf",short:"Red snapper in bright tomato-olive-caper sauce.",time:"45–50 min",servings:"4",ingredients:["Red snapper","Tomatoes, onion, garlic","Olives, capers, jalapeños","Oregano, olive oil, lime"],steps:["Make sauce, nestle fish, bake or simmer.","Serve with rice and lime."],tip:"Sauce should be bright and briny."},
      {id:47,name:"Arroz a la Tumbada",region:"Gulf",short:"Veracruz seafood rice with tomatoes, chiles, and mixed seafood.",time:"45 min",servings:"4–6",ingredients:["Rice","Mixed seafood","Tomato, onion, garlic, chile","Fish stock, cilantro, lime"],steps:["Cook rice with tomato base.","Add seafood near the end."],tip:"Don’t overcook the seafood."},
      {id:48,name:"Camarones a la Diabla",region:"Gulf",short:"Shrimp in fiery red chile sauce — ‘deviled’ shrimp.",time:"25 min",servings:"4",ingredients:["Large shrimp","Árbol or guajillo chiles, tomato, garlic, onion"],steps:["Make chile sauce, cook shrimp just until pink.","Serve with rice or tortillas."],tip:"Adjust árbol chiles for heat."},
      {id:49,name:"Pescado Zarandeado",region:"Gulf",short:"Butterflied grilled fish with chile-mayo or adobo marinade.",time:"40 min",servings:"4",ingredients:["Whole fish, butterflied","Mayo or adobo, chile, garlic, lime"],steps:["Rub with marinade. Grill until charred and cooked.","Serve with lime and tortillas."],tip:"Mayo keeps fish moist and creates a crust."},
      {id:50,name:"Chilpachole de Jaiba",region:"Gulf",short:"Spicy Veracruz crab soup with tomatoes, chiles, and epazote.",time:"50 min",servings:"4–6",ingredients:["Crab","Tomatoes, onion, garlic, chipotle","Epazote, stock, lime"],steps:["Make chile-tomato base. Add stock and crab.","Serve with lime and tortillas."],tip:"Fresh crab is ideal; good canned works."},

      // CENTRAL VALLEY CA (including breakfast)
      {id:51,name:"Steak Ranchero (Valley Style)",region:"Central Valley CA",short:"Thin steak in mild ranchero sauce of tomatoes, onions, and peppers — with thick flour tortillas.",time:"35 min",servings:"4",ingredients:["Thin-cut steak","Onion, bell peppers, tomatoes","Garlic, cumin","Thick flour tortillas, rice, beans"],steps:["Sear steak. Make chunky sauce with vegetables.","Return steak to sauce. Serve with thick flour tortillas."],tip:"Valley flour tortillas are often thicker and irregular."},
      {id:52,name:"Chile Verde",region:"Central Valley CA",short:"Tender pork in bright tomatillo and green chile sauce — California Mexican staple.",time:"2–2.5 hrs",servings:"6–8",ingredients:["Pork shoulder cubes","Tomatillos, roasted green chiles","Onion, garlic, cumin, oregano","Cilantro, lime"],steps:["Brown pork. Blend green sauce.","Simmer until tender. Finish with cilantro and lime."],tip:"Freezes beautifully for burritos and plates."},
      {id:53,name:"Chile Colorado",region:"Central Valley CA",short:"Cubed beef or pork in smooth red chile gravy — classic Fresno plate and burrito filling.",time:"2 hrs",servings:"6",ingredients:["Beef chuck or pork cubes","Guajillo and ancho chiles","Onion, garlic, cumin, oregano"],steps:["Blend chile sauce. Brown meat, simmer in sauce until tender."],tip:"Strain for restaurant-smooth texture."},
      {id:54,name:"Central Valley Super Burrito",region:"Central Valley CA",short:"Oversized foil-wrapped burrito with rice, beans, and meat — Highway 99 favorite.",time:"20 min",servings:"2 large",ingredients:["Extra-large flour tortillas","Rice, beans, asada/carnitas/chile verde","Cheese, salsa, guacamole, crema"],steps:["Layer fillings, roll tightly, wrap in foil."],tip:"Often bigger and more rice-bean heavy than Mission style."},
      {id:55,name:"Wet Burrito (Mojado)",region:"Central Valley CA",short:"Burrito smothered in red or green sauce and melted cheese.",time:"25 min",servings:"2–4",ingredients:["Large flour tortillas","Rice, beans, meat","Enchilada or chile verde sauce","Shredded cheese, crema"],steps:["Roll burritos, cover with sauce and cheese.","Bake until bubbly."],tip:"Use good red sauce for best results."},
      {id:56,name:"Menudo (Weekend Breakfast)",region:"Central Valley CA",short:"Tripe soup in red chile broth — beloved Valley weekend breakfast, often served only on Saturday and Sunday mornings.",time:"3–4 hrs",servings:"8",ingredients:["2–3 lbs beef tripe, cleaned and cut","Optional beef feet or tendons","Guajillo/ancho chile base","Onion, garlic, oregano, optional hominy","Garnishes: chopped onion, cilantro, lime, oregano, crushed chile"],steps:["Simmer tripe (and feet if using) until very tender, 2–3 hours. Skim well.","Add blended chile sauce and seasonings; simmer longer. Add hominy if using.","Serve hot with the classic garnishes on the side."],tip:"A classic Central Valley weekend breakfast. Many restaurants serve it only on Saturdays and Sundays."},
      {id:57,name:"Gorditas (Valley Style)",region:"Central Valley CA",short:"Thick masa pockets stuffed with beans, chicharrón, or chile — especially popular in the Valley.",time:"40 min",servings:"4–6",ingredients:["Masa harina, water, optional lard","Fillings: beans, chicharrón, picadillo, chile verde","Lettuce, salsa, crema"],steps:["Cook thick masa disks, split, and stuff."],tip:"Valley versions are often smaller and a bit fattier."},
      {id:58,name:"Mulitas",region:"Central Valley CA",short:"Two corn tortillas with melted cheese and meat, griddled crispy — Fresno taqueria favorite.",time:"20 min",servings:"4",ingredients:["Corn tortillas","Cheese, cooked meat","Onion, cilantro, salsa"],steps:["Sandwich cheese and meat between tortillas.","Griddle until crisp and cheese melts."],tip:"Cheese is the glue; medium heat prevents burning."},
      {id:59,name:"Vampiros",region:"Central Valley CA",short:"Open-faced grilled tortilla with melted cheese and meat — crispy Valley taqueria item.",time:"15 min",servings:"4",ingredients:["Corn tortillas","Cheese, meat","Onion, cilantro, salsa, lime"],steps:["Griddle tortilla, melt cheese, top with meat and garnishes."],tip:"Keep the tortilla flat and crispy."},
      {id:60,name:"Quesabirria",region:"Central Valley CA",short:"Birria tacos with melted cheese + consomé for dipping — huge in Fresno.",time:"20 min",servings:"4–6",ingredients:["Corn tortillas","Birria meat, cheese","Consomé, onion, cilantro, lime"],steps:["Dip tortillas in fat/consomé, griddle with cheese and meat.","Serve with consomé."],tip:"Consomé dip is mandatory."},
      {id:61,name:"Torta (Valley Style)",region:"Central Valley CA",short:"Mexican sandwich on telera/bolillo with beans, meat, avocado, and more.",time:"15 min",servings:"2–4",ingredients:["Telera or bolillo rolls","Beans, asada/milanesa/carnitas","Avocado, tomato, onion, jalapeño, mayo"],steps:["Spread beans and mayo, layer fillings, press."],tip:"Balance of creamy beans, savory meat, and fresh toppings."},
      {id:62,name:"Chiles Rellenos",region:"Central Valley CA",short:"Roasted poblanos stuffed with cheese, battered, and fried — classic Fresno plate.",time:"50 min",servings:"4",ingredients:["Poblano chiles","Jack or queso fresco","Egg batter, flour","Tomato or ranchero sauce"],steps:["Roast, stuff, batter, and fry.","Serve with sauce, rice, and beans."],tip:"Hot oil helps batter set quickly."},
      {id:63,name:"Lengua or Cabeza",region:"Central Valley CA",short:"Tender beef tongue or head meat — prized at Valley taquerías.",time:"3–4 hrs",servings:"6–8",ingredients:["Beef tongue or cabeza","Onion, garlic, bay, salt","Tortillas, onion, cilantro, salsa"],steps:["Simmer until very tender. Chop and optionally sear.","Serve in tacos or plates."],tip:"Tongue should be fork-tender."},

      // CENTRAL VALLEY BREAKFAST
      {id:64,name:"Chilaquiles (Valley Style)",region:"Central Valley CA",short:"Crispy tortilla chips simmered in red or green salsa, topped with eggs, crema, and cheese — Valley breakfast classic.",time:"25 min",servings:"4",ingredients:["Corn tortilla chips or cut tortillas","Red or green salsa","Eggs (fried or scrambled)","Crema, queso fresco, onion, cilantro","Optional: asada, chicken, or chorizo"],steps:["Simmer chips briefly in warm salsa until softened but not mushy.","Top with eggs, crema, cheese, onion, and cilantro.","Add meat if desired."],tip:"Don’t over-soak the chips — they should still have some texture."},
      {id:65,name:"Huevos Rancheros",region:"Central Valley CA",short:"Fried eggs on lightly fried tortillas with warm ranchero sauce, beans, and cheese — diner and home breakfast staple.",time:"20 min",servings:"2–4",ingredients:["Eggs","Corn or flour tortillas","Ranchero or tomato-chile sauce","Refried beans, queso fresco or Jack, avocado optional"],steps:["Warm or lightly fry tortillas. Warm sauce and beans.","Fry eggs sunny-side or over-easy.","Assemble: tortilla, beans, eggs, sauce, cheese."],tip:"Sauce should be warm and spooned generously over the eggs."},
      {id:66,name:"Huevos con Chorizo",region:"Central Valley CA",short:"Scrambled eggs with Mexican chorizo — simple, flavorful Valley breakfast or taco filling.",time:"15 min",servings:"3–4",ingredients:["1/2–3/4 lb Mexican chorizo","6 eggs","Onion optional","Warm tortillas, salsa, beans"],steps:["Cook chorizo, breaking it up, until cooked through.","Add beaten eggs and scramble together.","Serve with tortillas, salsa, and beans."],tip:"Drain excess fat from chorizo if it is very oily."},
      {id:67,name:"Breakfast Burrito (Valley Style)",region:"Central Valley CA",short:"Large flour tortilla filled with eggs, potatoes, chorizo or asada, cheese, and salsa — grab-and-go Valley favorite.",time:"25 min",servings:"2–4",ingredients:["Large flour tortillas","Scrambled eggs","Diced potatoes (fried or roasted)","Chorizo, asada, or bacon","Cheese, salsa, optional beans and crema"],steps:["Cook fillings. Warm tortillas.","Layer eggs, potatoes, meat, cheese, and salsa. Roll tightly."],tip:"These are often huge and meant to keep you full for farm or work shifts."},
      {id:68,name:"Huevos a la Mexicana",region:"Central Valley CA",short:"Eggs scrambled with tomato, onion, and chile — light, fresh, and very common at Valley tables.",time:"15 min",servings:"2–4",ingredients:["6 eggs","Tomato, white onion, jalapeño or serrano","Oil, salt","Tortillas, beans, salsa optional"],steps:["Sauté onion, chile, and tomato until softened.","Add beaten eggs and scramble gently.","Serve with warm tortillas."],tip:"Don’t overcook the eggs — keep them soft."},
      {id:69,name:"Nopales con Huevos",region:"Central Valley CA",short:"Scrambled eggs with tender cactus paddles — healthy and traditional breakfast found in Valley homes and restaurants.",time:"25 min",servings:"3–4",ingredients:["Fresh or jarred nopales, cleaned and diced","Eggs","Onion, tomato, jalapeño optional","Oil, salt","Tortillas"],steps:["Cook nopales until no longer slimy (boil or sauté).","Sauté with onion and tomato if using.","Scramble in the eggs. Serve with tortillas."],tip:"Rinse and cook nopales well to reduce mucilage."},
      {id:70,name:"Machaca Breakfast Burrito or Plate",region:"Central Valley CA",short:"Northern-style dried beef with eggs, often served as a plate or in a large Valley-style breakfast burrito.",time:"20 min",servings:"3–4",ingredients:["Machaca or leftover shredded asada","Eggs","Onion, chile","Large flour tortillas or rice and beans for plate"],steps:["Sauté onion and chile with machaca.","Scramble in eggs.","Serve on a plate with beans/rice or wrap in a large tortilla."],tip:"A bridge between Northern Mexican and Central Valley breakfast traditions."},
      {id:71,name:"Costillas con Huevo / Steak & Eggs",region:"Central Valley CA",short:"Pork ribs or thin steak with fried eggs — hearty Valley breakfast plate often with beans and tortillas.",time:"30–40 min",servings:"2–4",ingredients:["Pork ribs or thin steak","Eggs","Salt, pepper, garlic","Beans, tortillas, salsa"],steps:["Season and cook the meat until done.","Fry eggs.","Serve together with warm beans, tortillas, and salsa."],tip:"Simple, filling, and very common in home and diner breakfasts."},

      // STREET & TRUCK
      {id:72,name:"Street Tacos – Carne Asada",region:"Street Food",short:"Small double corn tortillas, finely chopped grilled steak, onion, cilantro, salsa.",time:"30 min + marinade",servings:"12–16 tacos",ingredients:["Skirt/flank steak, marinated","Small corn tortillas","Onion, cilantro, salsa, lime"],steps:["Grill, chop finely.","Fill double tortillas. Top and serve."],tip:"Double tortillas; meat chopped small."},
      {id:73,name:"Tacos al Pastor",region:"Street Food",short:"Marinated pork with pineapple — Mexico City street icon.",time:"1 hr + marinate",servings:"6–8",ingredients:["Pork shoulder slices","Guajillo/ancho, pineapple juice, spices","Pineapple, tortillas, onion, cilantro"],steps:["Marinate, grill with pineapple, chop.","Serve on double tortillas."],tip:"Home method uses grill or cast-iron."},
      {id:74,name:"Suadero Tacos",region:"Street Food",short:"Slow-cooked, plancha-finished beef with crispy edges.",time:"2.5–3 hrs",servings:"6–8",ingredients:["Suadero or plate meat","Onion, garlic, bay","Lard, tortillas, onion, cilantro, salsa"],steps:["Simmer until tender. Sear on plancha.","Serve on double tortillas."],tip:"Long simmer + hard sear."},
      {id:75,name:"Tacos de Carnitas",region:"Street Food",short:"Chopped carnitas on small corn tortillas with classic toppings.",time:"15 min",servings:"8–10",ingredients:["Warm carnitas","Small corn tortillas","Onion, cilantro, salsa, lime"],steps:["Warm/chop carnitas. Fill tortillas and top."],tip:"A little cooking fat on the tortilla is authentic."},
      {id:76,name:"Tacos de Birria",region:"Street Food",short:"Shredded birria on corn tortillas, often with consomé.",time:"15 min",servings:"6–8",ingredients:["Birria meat","Corn tortillas","Consomé, onion, cilantro, lime"],steps:["Fill (or dip-and-griddle) tortillas. Serve with consomé."],tip:"Consomé is half the experience."},
      {id:77,name:"Elote",region:"Street Food",short:"Grilled corn with mayo/crema, cotija, chili, and lime.",time:"20 min",servings:"4",ingredients:["Ears of corn","Mayo or crema","Cotija, chili powder/Tajín, lime"],steps:["Grill, brush with mayo, roll in cheese and chile, add lime."],tip:"For esquites, cut kernels into a cup."},
      {id:78,name:"Tacos de Tripas",region:"Street Food",short:"Crispy-fried beef intestines — bold street favorite.",time:"2+ hrs",servings:"4–6",ingredients:["Cleaned tripas","Onion, garlic","Oil, tortillas, onion, cilantro, salsa"],steps:["Simmer until tender, then fry crispy. Chop and serve."],tip:"Cleaning and long simmer are essential."},
      {id:79,name:"Tacos de Chorizo",region:"Street Food",short:"Mexican chorizo on small tortillas with classic toppings.",time:"20 min",servings:"4–6",ingredients:["Mexican chorizo","Small corn tortillas","Onion, cilantro, salsa"],steps:["Cook chorizo, fill tortillas, top."],tip:"Use fresh Mexican-style chorizo."},
      {id:80,name:"Tacos de Papa",region:"Street Food",short:"Potato-filled tacos, often fried crisp — vegetarian street classic.",time:"35 min",servings:"4–6",ingredients:["Boiled potatoes","Onion, garlic, optional chile","Corn tortillas, oil","Lettuce, salsa, crema, cheese"],steps:["Season potato, fill and fry tortillas. Top and serve."],tip:"Great meatless option; also called tacos dorados when fully crispy."},
      {id:81,name:"Agua Fresca",region:"Street Food",short:"Refreshing horchata, jamaica, or tamarindo — every street stand has them.",time:"20 min + chill",servings:"6–8",ingredients:["Rice + cinnamon (horchata) or hibiscus or tamarind","Sugar, water, optional milk/vanilla"],steps:["Prepare chosen base, sweeten, chill, serve over ice."],tip:"Adjust sweetness; meant to be light and thirst-quenching."},
      {id:82,name:"Chicharrones Preparados",region:"Street Food",short:"Crispy pork rinds or flour puffs dressed with salsa, cabbage, avocado, and crema.",time:"10 min",servings:"2–4",ingredients:["Chicharrones or chicharrón de harina","Salsa, cabbage, avocado, crema, lime, Tajín"],steps:["Toss or shake with toppings. Eat immediately."],tip:"Work fast before they soften."}
    ];

    let currentRegion = "all";
    let searchQuery = "";
    const grid = document.getElementById("recipesGrid");
    const searchInput = document.getElementById("searchInput");
    const regionBtns = document.querySelectorAll(".region-btn");
    const modalOverlay = document.getElementById("modalOverlay");
    const closeModalBtn = document.getElementById("closeModal");

    function renderRecipes() {
      const filtered = recipes.filter(r => {
        const matchesRegion = currentRegion === "all" || r.region === currentRegion;
        const q = searchQuery.toLowerCase();
        const matchesSearch = !q || r.name.toLowerCase().includes(q) || r.short.toLowerCase().includes(q) || r.region.toLowerCase().includes(q) || (r.ingredients && r.ingredients.some(i => i.toLowerCase().includes(q)));
        return matchesRegion && matchesSearch;
      });
      if (filtered.length === 0) {
        grid.innerHTML = '<div class="no-results">No recipes found. Try a different search or region.</div>';
        return;
      }
      grid.innerHTML = filtered.map(r => `
        <div class="recipe-card" data-id="${r.id}">
          <div class="card-header"></div>
          <div class="card-body">
            <div class="card-region">${r.region}</div>
            <div class="card-title">${r.name}</div>
            <div class="card-desc">${r.short}</div>
            <div class="card-meta"><span>⏱ ${r.time}</span><span>🍽 ${r.servings}</span></div>
          </div>
        </div>`).join("");
      document.querySelectorAll(".recipe-card").forEach(card => {
        card.addEventListener("click", () => openModal(parseInt(card.dataset.id)));
      });
    }

    function openModal(id) {
      const r = recipes.find(x => x.id === id);
      if (!r) return;
      document.getElementById("modalTitle").textContent = r.name;
      document.getElementById("modalRegion").textContent = r.region + " • " + r.time + " • Serves " + r.servings;
      document.getElementById("modalBody").innerHTML = `
        <div class="section-title">🛒 Ingredients</div>
        <ul class="ingredients">${r.ingredients.map(i => `<li>${i}</li>`).join("")}</ul>
        <div class="section-title">👨‍🍳 Steps</div>
        <ol class="steps">${r.steps.map(s => `<li>${s}</li>`).join("")}</ol>
        ${r.tip ? `<div class="tips"><strong>Tip:</strong> ${r.tip}</div>` : ""}`;
      modalOverlay.classList.add("open");
      document.body.style.overflow = "hidden";
    }

    function closeModal() {
      modalOverlay.classList.remove("open");
      document.body.style.overflow = "";
    }

    regionBtns.forEach(btn => {
      btn.addEventListener("click", () => {
        regionBtns.forEach(b => b.classList.remove("active"));
        btn.classList.add("active");
        currentRegion = btn.dataset.region;
        renderRecipes();
      });
    });
    searchInput.addEventListener("input", e => { searchQuery = e.target.value; renderRecipes(); });
    closeModalBtn.addEventListener("click", closeModal);
    modalOverlay.addEventListener("click", e => { if (e.target === modalOverlay) closeModal(); });
    document.addEventListener("keydown", e => { if (e.key === "Escape") closeModal(); });

    const themeToggle = document.getElementById("themeToggle");
    function setTheme(theme) {
      document.documentElement.setAttribute("data-theme", theme);
      themeToggle.textContent = theme === "light" ? "🌙" : "☀️";
    }
    setTheme("dark");
    themeToggle.addEventListener("click", () => {
      const current = document.documentElement.getAttribute("data-theme");
      setTheme(current === "dark" ? "light" : "dark");
    });

    renderRecipes();